# DLL++ Library: dlat.to.install
import os
import subprocess

def compile_pipeline(dlat_file):
    if not dlat_file.endswith('.dlat'):
        print("[-] Ошибка: Файл должен иметь расширение .dlat")
        return

    py_file = dlat_file.replace('.dlat', '.py')
    
    print(f"[*] Шаг 1: Конвертация {dlat_file} в Python код...")
    
    # Логика конвертации синтаксиса
    with open(dlat_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    with open(py_file, 'w', encoding='utf-8') as f:
        f.write("# Generated by DLL++ Compiler\n")
        f.write("import os, sys\n")
        f.write(f"sys.path.append('modules')\n") # Чтобы EXE видел библиотеки
        
        for line in lines:
            if "library=:" in line:
                lib = line.split('=:')[1].split(':')[0]
                f.write(f"import {lib.replace('.', '_')} # DLL++ Import\n")
            # Здесь можно добавить замену других команд DLL++ на Python код
    
    print(f"[+] Шаг 2: Создание EXE через PyInstaller...")
    try:
        # --noconsole делает запуск скрытым (идеально для системных программ)
        subprocess.run(f"pyinstaller --onefile --noconsole {py_file}", shell=True)
        print(f"===[ УСПЕХ ]===")
        print(f"Проект {dlat_file} теперь стал мощным системным EXE!")
    except Exception as e:
        print(f"[-] Ошибка сборки: {e}")

# Команда: dll}bat{=dlat.to.install(build):my_system_tool.dlat: